services:
  ckan:
    image: thepaeth/ckan-dev:2.10.7
    build: 
      context: ckan-dev/
      args:
        - BASE=dev
        - CKAN_REF=ckan-2.10.7
    restart: unless-stopped
    container_name: ckan-dev
    ports:
      - "5001:5000"
    volumes:
      - ./src_extensions:/srv/app/src_extensions
      - ./ckan_conf:/srv/app/conf
      - ./storage:/var/lib/ckan
    environment:
      CKAN_SITE_URL: http://localhost:5001
      TEST_CKAN_SQLALCHEMY_URL: postgresql://ckan:${POSTGRES_PASSWORD}@db/ckan
      TEST_CKAN_DATASTORE_WRITE_URL: postgresql://ckan:${POSTGRES_PASSWORD}@db/datastore
      TEST_CKAN_DATASTORE_READ_URL: postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@db/datastore
      TEST_CKAN_REDIS_URL: redis://redis:6379/0
      TEST_CKAN_SOLR_URL: http://solr:8983/solr/ckan
    depends_on:
      - db
      - redis

  db:
    container_name: db
    restart: unless-stopped
    build:
      context: postgresql/
      args:
        - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=${TZ}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-ckan}", "-d", "${POSTGRES_DB:-ckan}"]
     
  solr:
    container_name: solr
    image: ckan/ckan-solr:2.10-solr8
    restart: unless-stopped
    volumes:
      - solr_data:/var/solr
    environment:
      - TZ=${TZ}
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:8983/solr/"]

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"]


volumes:
  ckan_conf:
  pg_data:
  solr_data:

